return {
	"catppuccin/nvim",
	lazy = false,
	name = "catppuccin",
	priority = 1000,
	opts = {
		flavour = "macchiato",
		background = "mocha",
		term_colors = true,
		transparent_background = true,
		no_italic = true,
		integrations = {
			cmp = true,
			gitsigns = true,
			nvimtree = true,
			treesitter = true,
			mason = true,
			telescope = {
				enabled = true,
			},
			indent_blankline = {
				enabled = true,
				scope_color = "",
				colored_indent_levels = false,
			},
			styles = {
				comments = { "italic" },
			},
			native_lsp = {
				enabled = true,
				virtual_text = {
					errors = { "italic" },
					hints = { "italic" },
					warnings = { "italic" },
					information = { "italic" },
				},
				underlines = {
					errors = { "underline" },
					hints = { "underline" },
					warnings = { "underline" },
					information = { "underline" },
				},
				inlay_hints = {
					background = true,
				},
			},
		},
		custom_highlights = function(C)
			return {
				CmpBorder = { fg = "#3e4145" },
				Cursor = { fg = "#cc9900", bg = "#339966" },
				CursorLine = { bg = "#252525" },

				CmpItemKindSnippet = { fg = C.base, bg = C.mauve },
				CmpItemKindKeyword = { fg = C.base, bg = C.red },
				CmpItemKindText = { fg = C.base, bg = C.teal },
				CmpItemKindMethod = { fg = C.base, bg = C.blue },
				CmpItemKindConstructor = { fg = C.base, bg = C.blue },
				CmpItemKindFunction = { fg = C.base, bg = C.blue },
				CmpItemKindFolder = { fg = C.base, bg = C.blue },
				CmpItemKindModule = { fg = C.base, bg = C.blue },
				CmpItemKindConstant = { fg = C.base, bg = C.peach },
				CmpItemKindField = { fg = C.base, bg = C.green },
				CmpItemKindProperty = { fg = C.base, bg = C.green },
				CmpItemKindEnum = { fg = C.base, bg = C.green },
				CmpItemKindUnit = { fg = C.base, bg = C.green },
				CmpItemKindClass = { fg = C.base, bg = C.yellow },
				CmpItemKindVariable = { fg = C.base, bg = C.flamingo },
				CmpItemKindFile = { fg = C.base, bg = C.blue },
				CmpItemKindInterface = { fg = C.base, bg = C.yellow },
				CmpItemKindColor = { fg = C.base, bg = C.red },
				CmpItemKindReference = { fg = C.base, bg = C.red },
				CmpItemKindEnumMember = { fg = C.base, bg = C.red },
				CmpItemKindStruct = { fg = C.base, bg = C.blue },
				CmpItemKindValue = { fg = C.base, bg = C.peach },
				CmpItemKindEvent = { fg = C.base, bg = C.blue },
				CmpItemKindOperator = { fg = C.base, bg = C.blue },
				CmpItemKindTypeParameter = { fg = C.base, bg = C.blue },
				CmpItemKindCopilot = { fg = C.base, bg = C.teal },
			}
		end,
		color_overrides = {
			macchiato = {
				rosewater = "#F5B8AB",
				flamingo = "#F29D9D",
				pink = "#AD6FF7",
				mauve = "#FF8F40",
				red = "#E66767",
				maroon = "#EB788B",
				peach = "#FAB770",
				yellow = "#FACA64",
				green = "#70CF67",
				teal = "#4CD4BD",
				sky = "#61BDFF",
				sapphire = "#4BA8FA",
				blue = "#00BFFF",
				lavender = "#00BBCC",
				text = "#C1C9E6",
				subtext1 = "#A3AAC2",
				subtext0 = "#8E94AB",
				overlay2 = "#7D8296",
				overlay1 = "#676B80",
				overlay0 = "#464957",
				surface2 = "#3A3D4A",
				surface1 = "#2F313D",
				surface0 = "#1D1E29",
				base = "#0b0b12",
				mantle = "#11111a",
				crust = "#191926",
			},
		},
	},
	config = function(_, opts)
		require("catppuccin").setup(opts)
		vim.api.nvim_command("colorscheme catppuccin-macchiato")
	end,
}
